# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 817d4d1568bd401c8f3899c2c6a5a3b6fa227b02df142a095c03ef31228acb09e5cd7a3dbd2e9087c01db35049fa316e9856de425b6509b64cba7fc31c92cc7b

test:
  secret_key_base: ea61a2c2b42e4b838701ac009ddf4e001c5f2a5898f2b5c883a9b5240e5848535a3332188be37537895828b5ff872e6792ed9e5a48f9073f5fe844ac15fa220f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
